-- MySQL Script generated by MySQL Workbench
-- Tue 01 Aug 2017 04:06:56 PM BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CV DataBase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CV DataBase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CV DataBase` DEFAULT CHARACTER SET utf8 ;
USE `CV DataBase` ;

-- -----------------------------------------------------
-- Table `CV DataBase`.`Star`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CV DataBase`.`Star` (
  `name` VARCHAR(10) NOT NULL,
  `mass` DOUBLE NOT NULL,
  `radius` DOUBLE NOT NULL,
  `system_inclination` DOUBLE NOT NULL,
  `using_atmospheric_model` VARCHAR(45) NOT NULL,
  `mag_inner_radius` DOUBLE NOT NULL,
  `mag_outer_radius` DOUBLE NOT NULL,
  `mag_mass_accretion_rate` DOUBLE NOT NULL,
  `mag_heating_rate` DOUBLE NOT NULL,
  `mag_minimum_temperature` DOUBLE NOT NULL,
  `mag_maximum_temperature` DOUBLE NOT NULL,
  `diskwind_inner_radius` DOUBLE NOT NULL,
  `diskwind_outer_radius` DOUBLE NOT NULL,
  `diskwind_maximum_height` DOUBLE NOT NULL,
  `coeficient_a` DOUBLE NOT NULL,
  `coeficient_b` DOUBLE NOT NULL,
  `disk_wind_lauching_angle` DOUBLE NOT NULL,
  `lambda` DOUBLE NOT NULL,
  `kappa` DOUBLE NOT NULL,
  `fiducial_density` DOUBLE NOT NULL,
  `mass_loss_rate` DOUBLE NOT NULL,
  `isothermal_disk_wind_temperature` DOUBLE NOT NULL,
  `transition_lower_level` DOUBLE NOT NULL,
  `transition_upper_level` DOUBLE NOT NULL,
  `central_line_frequency` DOUBLE NOT NULL,
  `grid_size` VARCHAR(20) NOT NULL,
  `time_stamp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`time_stamp`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
